services:
  inms-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: inms-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Iac@4336"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - inms_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Iac@4336", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  inms-api:
    build:
      context: ./Backend
      dockerfile: INMS.API/Dockerfile
    container_name: inms-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=inms-db,1433;Database=INMS_SLT;User Id=sa;Password=Iac@4336;TrustServerCertificate=True;
    ports:
      - "5289:8080"
    depends_on:
      inms-db:
        condition: service_healthy

volumes:
  inms_sql_data:
